build:
    environment:
        redis: false
        postgresql: false
        node: false
        php:
            version: '7.1'
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
                    -
                        command: phpcs-run
                        use_website_config: true
                    -
                        command: 'vendor/bin/phpunit --coverage-clover=var/report/clover.xml'
                        coverage:
                            file: 'var/report/clover.xml'
                            format: 'clover'
filter:
    excluded_paths:
        - 'tests/*'
        - 'vendor/*'
        - 'var/*'
checks:
    php: true
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
