dist: trusty
sudo: required

language: php
php:
  - 7.1

install:
  - composer install

before_script:
  - cp phpunit.xml.dist phpunit.xml

script:
# until this issue is open i disable npm test and use test-php and test-karma in place (issue:https://github.com/DevExpress/testcafe/issues/2195, original post: https://testcafe-discuss.devexpress.com/t/role-sometime-it-doesnt-seem-to-be-played/875/9)
#  - npm test
  - vendor/bin/phpunit -c phpunit.xml

notifications:
  email: false